import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { ROOT_DIR, buildUserscript } from '../scripts/build-userscript.ts';

test('builds a Tampermonkey userscript from src modules', async () => {
  const tempDir = mkdtempSync(path.join(os.tmpdir(), 'easy-pokelike-build-'));
  const outPath = path.join(tempDir, 'easy-pokelike.user.js');

  await buildUserscript({ outPath });

  const output = readFileSync(outPath, 'utf8');
  assert.ok(output.startsWith('// ==UserScript=='));
  assert.ok(output.includes('// ==/UserScript=='));
  assert.ok(output.includes('Generated by npm run build'));
  assert.ok(output.includes('(function()'));
  assert.equal(output.includes('\nimport '), false);
  assert.ok(output.includes('var EasyPokelikeStrategyUtils = (() => {'));
  assert.ok(output.includes("PANEL_TITLE: 'Easy Pokelike 9.5'"));
  assert.equal(output.includes('<strong>Engine 7</strong>'), false);
  assert.ok(output.includes('return EasyPokelikeStrategyUtils.foldText(text);'));
  assert.ok(
    output.includes('return EasyPokelikeStrategyUtils.normalizeItemName(name, ITEM_TRANSLATIONS);'),
  );
  assert.ok(output.includes('return EasyPokelikeStrategyUtils.normalizeTypeList(types);'));
  assert.ok(
    output.includes(
      'return EasyPokelikeStrategyUtils.getItemBoostType(normalizeItemName(itemName), ITEM_TYPE_MATCH);',
    ),
  );
  assert.ok(
    output.includes(
      'return EasyPokelikeStrategyUtils.isHealingItem(normalizeItemName(itemName), MAIN_CARRY_SUSTAIN_ITEMS);',
    ),
  );
  assert.ok(
    output.includes(
      'return EasyPokelikeStrategyUtils.isLowValueHeldItem(normalizeItemName(itemName), LOW_VALUE_HELD_ITEMS);',
    ),
  );
  assert.ok(
    output.indexOf('var EasyPokelikeStrategyUtils = (() => {') <
      output.indexOf('function normalizeTypeList(types)'),
  );

  execFileSync(process.execPath, ['--check', outPath], { cwd: ROOT_DIR, stdio: 'pipe' });
});

test('keeps the modular source files available', () => {
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'userscript.meta.js')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'README.md')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'types.d.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'manifest.json')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy-utils.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'catch-scoring.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'card-scoring.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'item-scoring.ts')));
  assert.ok(
    existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'progress-strategy.ts')),
  );
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'route-scoring.ts')));
  assert.ok(
    existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'starter-scoring.ts')),
  );
  assert.ok(
    existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'strategy', 'passive-scoring.ts')),
  );
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'team-utils.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'text-utils.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'lib', 'type-matchups.ts')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'parts', '00-runtime-hooks.js')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'core', 'parts', '06-initialization.js')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'src', 'data', 'generated', 'bundle-meta.json')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'docs', 'development.md')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'docs', 'strategy.md')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'docs', 'troubleshooting.md')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'docs', 'data-extraction.md')));
  assert.ok(existsSync(path.join(ROOT_DIR, 'docs', 'roadmap.md')));
});
