import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
export const ROOT_DIR = path.resolve(SCRIPT_DIR, '..');

interface CoreManifest {
  parts: string[];
}

export interface BuildUserscriptOptions {
  rootDir?: string;
  metaPath?: string;
  manifestPath?: string;
  corePath?: string;
  outPath?: string;
}

function parseCoreManifest(raw: string, manifestPath: string): CoreManifest {
  const parsed = JSON.parse(raw) as Partial<CoreManifest>;
  if (!Array.isArray(parsed.parts) || parsed.parts.length === 0) {
    throw new Error(`Core manifest has no parts: ${manifestPath}`);
  }
  if (parsed.parts.some((partPath) => typeof partPath !== 'string' || !partPath.trim())) {
    throw new Error(`Core manifest contains an invalid part path: ${manifestPath}`);
  }
  return { parts: parsed.parts };
}

async function readCoreSource(rootDir: string, options: BuildUserscriptOptions): Promise<string> {
  if (options.corePath) {
    return readFile(options.corePath, 'utf8');
  }

  const manifestPath = options.manifestPath || path.join(rootDir, 'src', 'core', 'manifest.json');
  const legacyCorePath = path.join(rootDir, 'src', 'core', 'easy-pokelike-core.js');

  if (!existsSync(manifestPath)) {
    return readFile(legacyCorePath, 'utf8');
  }

  const manifest = parseCoreManifest(await readFile(manifestPath, 'utf8'), manifestPath);
  const manifestDir = path.dirname(manifestPath);

  // The parts share one generated IIFE scope, so ordering is a behavioral contract.
  const chunks = await Promise.all(
    manifest.parts.map(async (partPath) => {
      const fullPath = path.resolve(manifestDir, partPath);
      return (await readFile(fullPath, 'utf8')).trimEnd();
    }),
  );
  return `${chunks.join('\n')}\n`;
}

function looksLikeWrappedIife(source: string): boolean {
  const trimmed = source.trim();
  return trimmed.startsWith('(function()') && trimmed.endsWith('})();');
}

function wrapCoreSource(core: string): string {
  if (looksLikeWrappedIife(core)) {
    return `${core.trimEnd()}\n`;
  }

  return `(function() {
    'use strict';

${core.trimEnd()}
})();
`;
}

export async function buildUserscript(options: BuildUserscriptOptions = {}): Promise<string> {
  const rootDir = options.rootDir || ROOT_DIR;
  const metaPath = options.metaPath || path.join(rootDir, 'src', 'userscript.meta.js');
  const outPath = options.outPath || path.join(rootDir, 'easy-pokelike.user.js');

  const [meta, core] = await Promise.all([
    readFile(metaPath, 'utf8'),
    readCoreSource(rootDir, options),
  ]);

  if (!meta.includes('// ==UserScript==') || !meta.includes('// ==/UserScript==')) {
    throw new Error(`Tampermonkey metadata block is incomplete: ${metaPath}`);
  }
  const wrappedCore = wrapCoreSource(core);

  const output = `${meta.trimEnd()}

// Generated by npm run build. Edit files in src/.
${wrappedCore.trimStart()}`;

  await writeFile(outPath, output, 'utf8');
  return outPath;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  buildUserscript()
    .then((outPath) => {
      console.log(`Built ${path.relative(ROOT_DIR, outPath)}`);
    })
    .catch((error: Error) => {
      console.error(error.stack || error.message);
      process.exitCode = 1;
    });
}
